###################################
# Basic configuration
###################################

# For windows compatibility
set windows-shell := ["C:\\Program Files\\Git\\bin\\sh.exe", "-c"]

# Ignore recipe lines beginning with #.
set ignore-comments

# Format justfile
j-fmt:
    just --fmt

###################################
# Update
###################################

# Update everything: Rust toolchain, project dependencies, and global tools
# Note: -i means "allow incompatible upgrades"
# Requires cargo-edit and cargo-update
update:
    cargo --version
    rustup update stable
    cargo upgrade -i allow
    cargo update
    cargo install-update -a

# Update Rust toolchain including nightly
update-rust-all:
    rustup update

###################################
# Formatter and Linter
###################################

# Format code
fmt:
    cargo +nightly fmt --all

# Lint code
lint:
    just fmt
    cargo +nightly clippy --all-targets --all-features

# Lint code allowing dead_code warnings
lint2:
    just fmt
    RUSTFLAGS="-A dead_code" cargo +nightly clippy --all-targets --all-features

###################################
# Tests
###################################

# Run tests
# --no-fail-fast: Do not exit the test run until all tests complete.
# cargo nextest run -p my-package
# cargo nextest run <test-name1> <test-name2>...
# cargo nextest run --no-capture
test FILTER='':
    cargo nextest run --no-fail-fast {{ FILTER }}

# Generate code coverage report
cov:
    CARGO_PROFILE_DEV_DEBUG_ASSERTIONS=false cargo +nightly llvm-cov nextest --branch --open

###################################
# Dependencies
###################################

# Add dependency to Cargo.toml
add package:
    cargo add {{ package }}

# Add dependency to Cargo.toml with specific features
add-features package +FEATURES:
    cargo add {{ package }} --features {{ FEATURES }}

# Install binary package globally
# Requires cargo-binstall
binstall package:
    cargo binstall {{ package }}

# List globally installed packages
list-global:
    cargo install --list

# Detect unused dependencies
machete:
    cargo machete

###################################
# Build
###################################

# Todo

###################################
# Utils
###################################

# Clean the target directory
clean:
    cargo clean

# Clean coverage artifacts
cov-clean:
    cargo llvm-cov clean

# Count lines of code
# To update, `go install github.com/boyter/scc/v3@latest`
scc:
    scc .
