set windows-shell := ["C:\\Program Files\\Git\\bin\\sh.exe", "-c"]
set ignore-comments

default:
    just --list

install:
    bun install

wasm:
    cd ../logic && wasm-pack build --target web --out-dir ../web/src/wasm

dev:
    bun run dev

check:
    bun run check

build:
    bun run build

preview:
    bun run preview

clean:
    rm -rf dist src/wasm/*
    touch src/wasm/.gitkeep
